import { History, Sparkles, Zap } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import AiRecommendationCard from '../components/AiRecommendationCard'
import AppShell from '../components/AppShell'
import api from '../services/api'
import { formatUtcTimestamp } from '../utils/time'

function AuditSkeleton() {
  return (
    <div className="grid gap-4 lg:grid-cols-3">
      {Array.from({ length: 3 }).map((_, index) => (
        <div key={index} className="panel animate-pulse p-5">
          <div className="h-4 w-24 rounded bg-white/10" />
          <div className="mt-4 h-7 w-40 rounded bg-white/10" />
          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            <div className="h-24 rounded-2xl bg-white/10" />
            <div className="h-24 rounded-2xl bg-white/10" />
          </div>
          <div className="mt-5 h-28 rounded-2xl bg-white/10" />
        </div>
      ))}
    </div>
  )
}

function AiAuditPage() {
  const [currentAudit, setCurrentAudit] = useState(null)
  const [history, setHistory] = useState([])
  const [isHistoryLoading, setIsHistoryLoading] = useState(true)
  const [isRunning, setIsRunning] = useState(false)
  const [applyingResourceName, setApplyingResourceName] = useState('')
  const [actionMessage, setActionMessage] = useState('')
  const [error, setError] = useState('')
  const [dismissed, setDismissed] = useState([])

  const loadHistory = async () => {
    setIsHistoryLoading(true)
    try {
      const { data } = await api.get('/ai/audit/history')
      setHistory(data)
    } catch {
      setHistory([])
      setError('Unable to load previous AI audits right now. Run a fresh audit after the backend recovers.')
    } finally {
      setIsHistoryLoading(false)
    }
  }

  useEffect(() => {
    loadHistory()
  }, [])

  const runAudit = async () => {
    setIsRunning(true)
    setError('')
    setActionMessage('')
    setDismissed([])

    try {
      const { data } = await api.post('/ai/audit')
      setCurrentAudit(data)
      await loadHistory()
    } catch (runAuditError) {
      setCurrentAudit(null)
      setError(
        runAuditError.response?.data?.message ||
          'Unable to run the AI waste audit right now. Please try again shortly.',
      )
    } finally {
      setIsRunning(false)
    }
  }

  const visibleRecommendations = useMemo(() => {
    const activeAudit = currentAudit || history[0] || null
    const recommendations = activeAudit?.recommendations || []
    return recommendations.filter((item) => !dismissed.includes(item.resourceName))
  }, [currentAudit, history, dismissed])

  const activeAudit = currentAudit || history[0] || null
  const applyOptimization = async (recommendation) => {
    if (!activeAudit?.auditId) {
      setError('No saved audit is available to queue an optimization action.')
      return
    }

    setApplyingResourceName(recommendation.resourceName)
    setError('')
    setActionMessage('')

    try {
      const { data } = await api.post(`/ai/audit/${activeAudit.auditId}/actions`, {
        resourceName: recommendation.resourceName,
        recommendedAction: recommendation.recommendedAction,
        recommendedInstanceType: recommendation.recommendedInstanceType,
      })
      setActionMessage(`${data.resourceName}: ${data.message}`)
    } catch (applyError) {
      setError(
        applyError.response?.data?.message ||
          'Unable to queue the optimization action right now.',
      )
    } finally {
      setApplyingResourceName('')
    }
  }

  return (
    <AppShell>
      <div className="space-y-6">
        <section className="panel overflow-hidden p-6">
          <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between">
            <div>
              <p className="text-sm uppercase tracking-[0.28em] text-slate-500">AI Waste Auditor</p>
              <h2 className="mt-2 text-3xl font-semibold text-white">Identify idle spend before finance closes the month.</h2>
              <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">
                Run a telemetry-aware waste audit to surface rightsizing, decommissioning, and savings opportunities generated by Spring AI.
              </p>
            </div>
            <button
              type="button"
              onClick={runAudit}
              disabled={isRunning}
              className="app-button app-button-primary inline-flex w-full items-center justify-center gap-3 rounded-2xl px-5 py-4 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto"
            >
              <Sparkles className="h-5 w-5" />
              {isRunning ? 'Evaluating Telemetry...' : 'Run AI Waste Audit'}
            </button>
          </div>
        </section>

        {error ? (
          <div className="rounded-2xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-100">
            {error}
          </div>
        ) : null}
        {actionMessage ? (
          <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100">
            {actionMessage}
          </div>
        ) : null}

        <section className="space-y-4">
          <div className="flex items-center gap-3">
            <Zap className="h-5 w-5 text-emerald-300" />
            <h3 className="text-xl font-semibold text-white">Recommended actions</h3>
          </div>

          {isRunning ? (
            <AuditSkeleton />
          ) : (
            <div className="grid gap-4 xl:grid-cols-3">
              {!visibleRecommendations.length ? (
                <div className="panel col-span-full p-5 text-sm text-slate-300">
                  {history.length || currentAudit
                    ? 'The latest audit did not return any recommendation items.'
                    : 'No audit recommendations are available yet. Run an AI waste audit to populate this panel.'}
                </div>
              ) : null}
              {visibleRecommendations.map((recommendation) => (
                <AiRecommendationCard
                  key={recommendation.resourceName}
                  recommendation={recommendation}
                  isApplying={applyingResourceName === recommendation.resourceName}
                  onApply={() => applyOptimization(recommendation)}
                  onDismiss={() =>
                    setDismissed((current) => [...current, recommendation.resourceName])
                  }
                />
              ))}
            </div>
          )}
        </section>

        <section className="panel p-5">
          <div className="flex items-center gap-3">
            <History className="h-5 w-5 text-indigo-300" />
            <h3 className="text-xl font-semibold text-white">Audit history</h3>
          </div>

          <div className="mt-5 space-y-3">
            {isHistoryLoading ? (
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">
                Loading audit history...
              </div>
            ) : null}
            {!isHistoryLoading && !history.length ? (
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">
                No saved audits are available yet.
              </div>
            ) : null}
            {history.map((item) => (
              <div
                key={item.auditId}
                className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 md:flex-row md:items-center md:justify-between"
              >
                <div>
                  <p className="text-sm font-semibold text-white">Audit #{item.auditId}</p>
                  <p className="mt-1 text-sm text-slate-400">{item.auditSummary}</p>
                </div>
                <div className="flex flex-col items-start gap-1 text-sm md:items-end">
                  <span className="rounded-full bg-emerald-400/15 px-3 py-1 font-semibold text-emerald-300">
                    ${Number(item.totalPotentialSavings || 0).toLocaleString()} potential savings
                  </span>
                  <span className="text-slate-500">
                    {formatUtcTimestamp(item.createdAt, 'en-US', {
                      dateStyle: 'medium',
                      timeStyle: 'short',
                    })}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </AppShell>
  )
}

export default AiAuditPage
